# Generated by Django 3.2.15 on 2022-09-09 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('area_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.area')),
            ],
            options={
                'db_table': 'ward',
            },
        ),
    ]
