# Generated by Django 3.2.15 on 2022-09-30 07:51

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('event_name', models.CharField(blank=True, max_length=100, null=True)),
                ('event_desc', models.TextField(blank=True, null=True)),
                ('event_location', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
        ),
    ]
