# Generated by Django 3.2.15 on 2022-09-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
