# Generated by Django 3.2.15 on 2022-09-30 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_eventmodel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='i',
            field=models.URLField(blank=True, null=True),
        ),
    ]
