# Generated by Django 3.2.15 on 2022-09-30 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20220930_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='created_by',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='intrested_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
