# Generated by Django 3.2.15 on 2022-09-30 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20220930_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventlikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_yes', models.IntegerField(blank=True, default=0, null=True)),
                ('event_no', models.IntegerField(blank=True, default=0, null=True)),
                ('event_maybe', models.IntegerField(blank=True, default=0, null=True)),
                ('eventid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.eventmodel')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
