# Generated by Django 3.2.15 on 2022-09-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventlikemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlikemodel',
            name='event_bool',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='eventlikemodel',
            name='event_char',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
