# Generated by Django 3.2.15 on 2022-10-04 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_auto_20220930_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='event_desc',
            new_name='event_description',
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='i',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='intrested_user',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
