# Generated by Django 3.2.15 on 2022-10-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20221004_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlikemodel',
            name='event_bool',
        ),
        migrations.RemoveField(
            model_name='eventlikemodel',
            name='event_char',
        ),
        migrations.RemoveField(
            model_name='eventlikemodel',
            name='event_maybe',
        ),
        migrations.RemoveField(
            model_name='eventlikemodel',
            name='event_no',
        ),
        migrations.RemoveField(
            model_name='eventlikemodel',
            name='event_yes',
        ),
        migrations.AddField(
            model_name='eventlikemodel',
            name='event_choice',
            field=models.CharField(blank=True, choices=[(0, 'YES'), (1, 'NO'), (2, 'MAYBE')], max_length=10, null=True),
        ),
    ]
