# Generated by Django 3.2.15 on 2022-10-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20221004_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlikemodel',
            name='event_choice',
            field=models.IntegerField(blank=True, choices=[(0, 'YES'), (1, 'NO'), (2, 'MAYBE')], max_length=10, null=True),
        ),
    ]
