# Generated by Django 3.2.15 on 2022-10-04 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_eventlikemodel_event_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='event_file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])]),
        ),
    ]
