# Generated by Django 3.2.15 on 2022-10-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventmodel_event_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='event_location',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='event_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='event_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='event_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
