# Generated by Django 3.2.15 on 2022-10-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20221004_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='location',
            new_name='envent_video',
        ),
    ]
