# Generated by Django 3.2.15 on 2022-10-06 08:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0012_rename_location_eventmodel_envent_video'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventlikemodel',
            unique_together={('userid', 'eventid')},
        ),
    ]
