# Generated by Django 3.2.15 on 2022-10-06 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projectowner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'ACTIVE'), (1, 'INACTIVE'), (2, 'COMPLETED'), (3, 'CANCELLED')], default=0, null=True),
        ),
    ]
