# Generated by Django 3.2.15 on 2022-10-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projecttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
