# Generated by Django 3.2.15 on 2022-11-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinvite',
            name='invite_status',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
