# Generated by Django 3.2.15 on 2022-12-12 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0003_broadcastmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomFCMDevice',
        ),
    ]
