# Generated by Django 3.2.15 on 2022-10-13 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stories_title', models.TextField(blank=True, null=True)),
                ('stories_discription', models.TextField(blank=True, null=True)),
                ('stories_start', models.DateTimeField(blank=True, null=True)),
                ('stories_end', models.DateTimeField(blank=True, null=True)),
                ('stories_file', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png', 'mp4', 'mov', 'mkv', 'avi'])])),
            ],
        ),
    ]
