# Generated by Django 3.2.15 on 2022-10-14 05:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0003_feedlikemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedLikeModel',
            new_name='StoriesLikeModel',
        ),
    ]
