# Generated by Django 3.2.15 on 2022-10-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_rename_feedlikemodel_storieslikemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storiesmodel',
            name='stories_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
