# Generated by Django 3.2.15 on 2022-11-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_storiesmodel_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='storiesmodel',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
