# Generated by Django 3.2.15 on 2022-11-10 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_storiesmodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storiesmodel',
            name='stories_file',
            field=models.FileField(default=1, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png', 'mp4', 'mov', 'mkv', 'avi'])]),
            preserve_default=False,
        ),
    ]
