# Generated by Django 3.2.15 on 2022-11-10 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_alter_storiesmodel_stories_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='storiesmodel',
            name='stories_files',
            field=models.FileField(default='giphy.gif', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png', 'mp4', 'mov', 'mkv', 'avi'])]),
        ),
        migrations.AlterField(
            model_name='storiesmodel',
            name='stories_file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png', 'mp4', 'mov', 'mkv', 'avi'])]),
        ),
    ]
