# Generated by Django 3.2.15 on 2022-11-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_auto_20221110_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storiesmodel',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
