# Generated by Django 3.2.15 on 2022-11-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_alter_storiesmodel_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(upload_to='')),
                ('image_url', models.URLField()),
            ],
        ),
    ]
