# Generated by Django 3.2.15 on 2022-11-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
