# Generated by Django 3.2.15 on 2022-11-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_alter_item_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
