# Generated by Django 3.2.15 on 2022-11-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0014_item_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_file',
            field=models.FileField(blank=True, default='1.jpg', upload_to=''),
        ),
    ]
