# Generated by Django 3.2.15 on 2022-11-14 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0015_alter_item_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_urls',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
