# Generated by Django 3.2.15 on 2022-09-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(blank=True, max_length=200, null=True)),
                ('video_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('video_name_m', models.CharField(blank=True, max_length=200, null=True)),
                ('video_desc_m', models.CharField(blank=True, max_length=200, null=True)),
                ('video_link', models.FileField(blank=True, null=True, upload_to='')),
                ('viewed', models.IntegerField(blank=True, default=0, null=True)),
                ('liked', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'video',
            },
        ),
    ]
