# Generated by Django 3.2.15 on 2022-09-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_videomodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='title2',
            field=models.TextField(blank=True, help_text='title2', null=True, verbose_name='title2'),
        ),
    ]
