# Generated by Django 3.2.15 on 2022-09-26 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_videomodel_title2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_title', models.TextField(blank=True, null=True)),
                ('feed_discription', models.TextField(blank=True, null=True)),
                ('feed_image', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])])),
            ],
            options={
                'db_table': 'feeds',
            },
        ),
    ]
