# Generated by Django 3.2.15 on 2022-10-12 06:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_feedlikemodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedlikemodel',
            unique_together={('feed_id', 'user_id')},
        ),
    ]
