# Generated by Django 3.2.15 on 2022-10-12 06:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0008_alter_feedlikemodel_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedlikemodel',
            old_name='feed_id',
            new_name='feed_ids',
        ),
        migrations.AlterUniqueTogether(
            name='feedlikemodel',
            unique_together={('feed_ids', 'user_id')},
        ),
    ]
