# Generated by Django 3.2.15 on 2022-10-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20221012_0648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedLikeModel',
        ),
    ]
