# Generated by Django 3.2.15 on 2022-10-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_feedcomments_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcomments',
            name='user_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
