# Generated by Django 3.2.15 on 2022-11-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertismentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_category', models.TextField()),
                ('ads_category_discription', models.TextField()),
            ],
        ),
    ]
