# Generated by Django 3.2.15 on 2022-09-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollmodel',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='related_polls', to='polls.Choice'),
        ),
    ]
