# Generated by Django 3.2.15 on 2022-10-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0003_alter_groupchatmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatmodel',
            name='text_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
