# Generated by Django 3.2.15 on 2022-11-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0008_message_groupint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='groupInt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
