# Generated by Django 3.2.15 on 2022-11-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0009_alter_message_groupint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['time']},
        ),
    ]
