# Generated by Django 3.2.15 on 2022-11-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0010_alter_message_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='context',
        ),
        migrations.RemoveField(
            model_name='message',
            name='group',
        ),
    ]
