# Generated by Django 3.2.15 on 2022-10-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20220920_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.IntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Citizen'), (3, 'Project_member')], null=True),
        ),
    ]
