# Generated by Django 3.2.15 on 2022-11-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
