# Generated by Django 3.2.15 on 2022-11-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.FileField(blank=True, default='index.png', null=True, upload_to=''),
        ),
    ]
